spring:
  main:
    lazy-initialization: true
  rsocket:
    server:
      port: 7002

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/users
    username: postgres
    password: postgres
    hikari.maximum-pool-size: 64
    hikari.auto-commit: false
    hikari.minimum-idle: 4
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8082


